name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            ~/.cache/pip
          key: pnpm-n-pip-cache-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-n-pip-cache-${{ hashFiles('pnpm-lock.yaml') }}
            pnpm-n-pip-cache-

      - name: Setup
        run: |
          pip install wheel setuptools pip -U
          npm i -g pnpm
          pnpm setup:ci

      - run: pnpm lint
      - run: python scripts/gen_pycompletions.py
      - run: pnpm test
